//! Windows PPM via PowrProf (AR-08: PowrProf is the ONLY CPU-policy
//! backend — powercfg.exe is never invoked as a backend, and HWP policy is
//! never dual-written via MSR).
//!
//! Reads are unconditional and work unelevated. Writes
//! (PowerWriteAC/DCValueIndex + PowerSetActiveScheme commit) exist only
//! under the `control` feature and require an elevated token — the
//! capability probe records `ppm.write_privileged` and the coordinator
//! gates on it (fail closed).

use std::sync::{Mutex, OnceLock};

use phelper_domain::error::PlatformError;
use phelper_domain::policy::{
    BoostPolicy, WindowsConfiguredPowerMode, WindowsEffectivePowerMode, WindowsPpmState,
    WindowsPpmValues,
};
use tracing::debug;
use windows::Win32::Foundation::{HLOCAL, LocalFree};
use windows::Win32::System::Power::{
    EFFECTIVE_POWER_MODE, EFFECTIVE_POWER_MODE_V1, EFFECTIVE_POWER_MODE_V2, PowerGetActiveScheme,
    PowerReadACValueIndex, PowerReadDCValueIndex, PowerRegisterForEffectivePowerModeNotifications,
};
#[cfg(feature = "control")]
use windows::Win32::System::Power::{
    PowerSetActiveScheme, PowerWriteACValueIndex, PowerWriteDCValueIndex,
};
use windows::core::GUID;

/// GUID_PROCESSOR_SUBGROUP 54533251-82be-4824-96c1-47b60b740d00.
const SUB_PROCESSOR: GUID = GUID::from_values(
    0x5453_3251,
    0x82be,
    0x4824,
    [0x96, 0xc1, 0x47, 0xb6, 0x0b, 0x74, 0x0d, 0x00],
);
/// GUID_PROCESSOR_PERFEPP 36687f9e-e3a5-4dbf-b1dc-15eb381c6863 (logical
/// processor 0's energy/performance preference; PERFEPP1 covers 1..n and
/// follows the same policy in practice).
const PERFEPP: GUID = GUID::from_values(
    0x3668_7f9e,
    0xe3a5,
    0x4dbf,
    [0xb1, 0xdc, 0x15, 0xeb, 0x38, 0x1c, 0x68, 0x63],
);
/// GUID_PROCESSOR_PERFEPP1 36687f9e-e3a5-4dbf-b1dc-15eb381c6864 — on
/// heterogeneous CPUs (13900HX) this is the processor-class-1 (E-core) EPP;
/// differs from PERFEPP only in the last byte.
const PERFEPP1: GUID = GUID::from_values(
    0x3668_7f9e,
    0xe3a5,
    0x4dbf,
    [0xb1, 0xdc, 0x15, 0xeb, 0x38, 0x1c, 0x68, 0x64],
);
/// GUID_PROCESSOR_PROCFREQMAX 75b0ae3f-bce0-45a7-8c89-c9611c25e100
/// (frequency ceiling in MHz; 0 = unlimited).
const PROCFREQMAX: GUID = GUID::from_values(
    0x75b0_ae3f,
    0xbce0,
    0x45a7,
    [0x8c, 0x89, 0xc9, 0x61, 0x1c, 0x25, 0xe1, 0x00],
);
/// GUID_PROCESSOR_PERFBOOSTMODE be337238-0d82-4146-a960-4f3749d470c7
/// (hidden setting; values = winnt.h PO_BOOST_* 0..=6 — see domain
/// BoostPolicy docs for the 3/4-aliasing and 5/6-rejection caveats).
const PERFBOOSTMODE: GUID = GUID::from_values(
    0xbe33_7238,
    0x0d82,
    0x4146,
    [0xa9, 0x60, 0x4f, 0x37, 0x49, 0xd4, 0x70, 0xc7],
);
/// GUID_PROCESSOR_PROCTHROTTLEMIN 893dee8e-2bef-41e0-89c6-b55d0929964c.
const PROCTHROTTLEMIN: GUID = GUID::from_values(
    0x893d_ee8e,
    0x2bef,
    0x41e0,
    [0x89, 0xc6, 0xb5, 0x5d, 0x09, 0x29, 0x96, 0x4c],
);
/// GUID_PROCESSOR_PROCTHROTTLEMAX bc5038f7-23e0-4960-96da-33abaf5935ec.
const PROCTHROTTLEMAX: GUID = GUID::from_values(
    0xbc50_38f7,
    0x23e0,
    0x4960,
    [0x96, 0xda, 0x33, 0xab, 0xaf, 0x59, 0x35, 0xec],
);

// Windows 11 user-configured power-mode overlay GUIDs. These APIs are not
// generated by windows-rs 0.62 yet, so the small PowrProf declarations are
// kept here. They are read-only in phelper; mode writes stay out of the
// product until Windows' voting/override semantics are modelled properly.
windows::core::link!(
    "powrprof.dll" "system"
    fn PowerGetUserConfiguredACPowerMode(power_mode_guid: *mut GUID) -> u32
);
windows::core::link!(
    "powrprof.dll" "system"
    fn PowerGetUserConfiguredDCPowerMode(power_mode_guid: *mut GUID) -> u32
);

const USER_MODE_BEST_EFFICIENCY: GUID = GUID::from_values(
    0x961c_c777,
    0x2547,
    0x4f9d,
    [0x81, 0x74, 0x7d, 0x86, 0x18, 0x1b, 0x8a, 0x7a],
);
const USER_MODE_BALANCED: GUID = GUID::zeroed();
const USER_MODE_BEST_PERFORMANCE: GUID = GUID::from_values(
    0xded5_74b5,
    0x45a0,
    0x4f42,
    [0x87, 0x37, 0x46, 0x34, 0x5c, 0x09, 0xc2, 0x38],
);

static EFFECTIVE_MODE: OnceLock<Mutex<Option<WindowsEffectivePowerMode>>> = OnceLock::new();
static EFFECTIVE_MODE_REGISTERED: OnceLock<bool> = OnceLock::new();

unsafe extern "system" fn effective_mode_callback(
    mode: EFFECTIVE_POWER_MODE,
    context: *const core::ffi::c_void,
) {
    if context.is_null() {
        return;
    }
    let Some(mode) = effective_mode_from_raw(mode.0) else {
        return;
    };
    // The context points at the process-lifetime OnceLock value below. It is
    // never freed, so callbacks that arrive after registration remain safe.
    let slot = unsafe { &*(context as *const Mutex<Option<WindowsEffectivePowerMode>>) };
    if let Ok(mut current) = slot.lock() {
        *current = Some(mode);
    }
}

fn effective_mode_from_raw(value: i32) -> Option<WindowsEffectivePowerMode> {
    Some(match value {
        0 => WindowsEffectivePowerMode::BatterySaver,
        1 => WindowsEffectivePowerMode::BetterBattery,
        2 => WindowsEffectivePowerMode::Balanced,
        3 => WindowsEffectivePowerMode::HighPerformance,
        4 => WindowsEffectivePowerMode::MaxPerformance,
        5 => WindowsEffectivePowerMode::GameMode,
        6 => WindowsEffectivePowerMode::MixedReality,
        _ => return None,
    })
}

fn effective_mode() -> Option<WindowsEffectivePowerMode> {
    let slot = EFFECTIVE_MODE.get_or_init(|| Mutex::new(None));
    let registered = *EFFECTIVE_MODE_REGISTERED.get_or_init(|| {
        let context =
            slot as *const Mutex<Option<WindowsEffectivePowerMode>> as *const core::ffi::c_void;
        let mut registration = std::ptr::null_mut();
        // V2 is preferred because it is the current API; V1 is the
        // compatibility fallback documented by PowrProf.
        let registered = unsafe {
            PowerRegisterForEffectivePowerModeNotifications(
                EFFECTIVE_POWER_MODE_V2,
                Some(effective_mode_callback),
                Some(context),
                &mut registration,
            )
            .is_ok()
        } || unsafe {
            PowerRegisterForEffectivePowerModeNotifications(
                EFFECTIVE_POWER_MODE_V1,
                Some(effective_mode_callback),
                Some(context),
                &mut registration,
            )
            .is_ok()
        };
        // The registration intentionally lives for the process lifetime. Its
        // callback writes only to the static lock; this avoids a race between
        // an asynchronous callback and a short-lived context during refresh.
        registered
    });
    if !registered {
        debug!("effective power-mode notification registration unavailable");
        return None;
    }
    // The contract says registration invokes the callback immediately, but
    // some Windows builds deliver it on a worker thread. Give that callback
    // a bounded opportunity to publish the initial value without turning
    // startup into a blocking probe.
    for _ in 0..3 {
        if let Some(mode) = slot.lock().ok().and_then(|current| *current) {
            return Some(mode);
        }
        std::thread::sleep(std::time::Duration::from_millis(1));
    }
    None
}

fn configured_mode_from_guid(guid: GUID) -> Option<WindowsConfiguredPowerMode> {
    if guid == USER_MODE_BEST_EFFICIENCY {
        Some(WindowsConfiguredPowerMode::BestEfficiency)
    } else if guid == USER_MODE_BALANCED {
        Some(WindowsConfiguredPowerMode::Balanced)
    } else if guid == USER_MODE_BEST_PERFORMANCE {
        Some(WindowsConfiguredPowerMode::BestPerformance)
    } else {
        None
    }
}

fn read_configured_mode(ac: bool) -> Result<WindowsConfiguredPowerMode, PlatformError> {
    let mut guid = GUID::zeroed();
    let rc = unsafe {
        if ac {
            PowerGetUserConfiguredACPowerMode(&mut guid)
        } else {
            PowerGetUserConfiguredDCPowerMode(&mut guid)
        }
    };
    if rc != 0 {
        return Err(PlatformError::Os(format!(
            "PowerGetUserConfigured{}PowerMode failed (win32 {rc})",
            if ac { "AC" } else { "DC" }
        )));
    }
    configured_mode_from_guid(guid).ok_or(PlatformError::Data(
        "unknown Windows user-configured power-mode GUID",
    ))
}

fn guid_string(guid: &GUID) -> String {
    format!(
        "{:08x}-{:04x}-{:04x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}",
        guid.data1,
        guid.data2,
        guid.data3,
        guid.data4[0],
        guid.data4[1],
        guid.data4[2],
        guid.data4[3],
        guid.data4[4],
        guid.data4[5],
        guid.data4[6],
        guid.data4[7]
    )
}

fn known_scheme_name(guid: &GUID) -> &'static str {
    match guid_string(guid).as_str() {
        "a1841308-3541-4fab-bc81-f71556f20b4a" => "Power saver",
        "381b4222-f694-41f0-9685-ff5bb260df2e" => "Balanced",
        "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c" => "High performance",
        _ => "Custom",
    }
}

/// EPP values in percent (0 = max performance, 100 = max efficiency),
/// split by power source as Windows stores them.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct EppReading {
    pub ac: u8,
    pub dc: u8,
}

fn active_scheme() -> Result<GUID, PlatformError> {
    unsafe {
        let mut scheme: *mut GUID = std::ptr::null_mut();
        let rc = PowerGetActiveScheme(None, &mut scheme);
        if rc.0 != 0 || scheme.is_null() {
            return Err(PlatformError::Os(format!(
                "PowerGetActiveScheme failed (win32 {})",
                rc.0
            )));
        }
        let guid = *scheme;
        // PowerGetActiveScheme allocates via LocalAlloc.
        let _ = LocalFree(Some(HLOCAL(scheme.cast())));
        Ok(guid)
    }
}

fn read_index(
    ac: bool,
    scheme: &GUID,
    subgroup: &GUID,
    setting: &GUID,
) -> Result<u32, PlatformError> {
    unsafe {
        let mut value: u32 = 0;
        // windows 0.62: AC variant returns WIN32_ERROR, DC variant u32.
        let rc = if ac {
            PowerReadACValueIndex(
                None,
                Some(scheme),
                Some(subgroup),
                Some(setting),
                &mut value,
            )
            .0
        } else {
            PowerReadDCValueIndex(
                None,
                Some(scheme),
                Some(subgroup),
                Some(setting),
                &mut value,
            )
        };
        if rc != 0 {
            return Err(PlatformError::Os(format!(
                "PowerRead{}ValueIndex failed (win32 {})",
                if ac { "AC" } else { "DC" },
                rc
            )));
        }
        Ok(value)
    }
}

/// Read current EPP from the active power scheme. Works unelevated (reads
/// are not privileged; only writes are).
pub(crate) fn read_epp() -> Result<EppReading, PlatformError> {
    let scheme = active_scheme()?;
    let ac = read_index(true, &scheme, &SUB_PROCESSOR, &PERFEPP)?;
    let dc = read_index(false, &scheme, &SUB_PROCESSOR, &PERFEPP)?;
    if ac > 100 || dc > 100 {
        return Err(PlatformError::Data("EPP out of 0-100 range"));
    }
    Ok(EppReading {
        ac: ac as u8,
        dc: dc as u8,
    })
}

/// Read the class-1 (E-core) EPP (PERFEPP1) from the active power scheme.
pub(crate) fn read_epp1() -> Result<EppReading, PlatformError> {
    let scheme = active_scheme()?;
    let ac = read_index(true, &scheme, &SUB_PROCESSOR, &PERFEPP1)?;
    let dc = read_index(false, &scheme, &SUB_PROCESSOR, &PERFEPP1)?;
    if ac > 100 || dc > 100 {
        return Err(PlatformError::Data("EPP1 out of 0-100 range"));
    }
    Ok(EppReading {
        ac: ac as u8,
        dc: dc as u8,
    })
}

/// Read the max-frequency ceiling on both rails (AC, DC).
pub(crate) fn read_max_freq_mhz_acdc() -> Result<(u32, u32), PlatformError> {
    let scheme = active_scheme()?;
    let ac = read_index(true, &scheme, &SUB_PROCESSOR, &PROCFREQMAX)?;
    let dc = read_index(false, &scheme, &SUB_PROCESSOR, &PROCFREQMAX)?;
    Ok((ac, dc))
}

/// Read PERFBOOSTMODE on both rails (AC, DC).
#[allow(dead_code)] // wired in W11 (PpmBackend reads)
pub(crate) fn read_boost_policy() -> Result<(BoostPolicy, BoostPolicy), PlatformError> {
    let scheme = active_scheme()?;
    let ac = read_index(true, &scheme, &SUB_PROCESSOR, &PERFBOOSTMODE)?;
    let dc = read_index(false, &scheme, &SUB_PROCESSOR, &PERFBOOSTMODE)?;
    let parse = |v: u32| {
        u8::try_from(v)
            .ok()
            .and_then(|b| BoostPolicy::try_from(b).ok())
            .ok_or(PlatformError::Data("unknown PERFBOOSTMODE value"))
    };
    Ok((parse(ac)?, parse(dc)?))
}

/// Read PROCTHROTTLEMIN on both rails (0..=100%).
pub(crate) fn read_min_performance() -> Result<(u8, u8), PlatformError> {
    let scheme = active_scheme()?;
    let ac = read_index(true, &scheme, &SUB_PROCESSOR, &PROCTHROTTLEMIN)?;
    let dc = read_index(false, &scheme, &SUB_PROCESSOR, &PROCTHROTTLEMIN)?;
    let parse = |v: u32| {
        u8::try_from(v)
            .ok()
            .filter(|v| *v <= 100)
            .ok_or(PlatformError::Data(
                "minimum processor state out of 0-100 range",
            ))
    };
    Ok((parse(ac)?, parse(dc)?))
}

/// Read PROCTHROTTLEMAX on both rails (0..=100%).
pub(crate) fn read_max_performance() -> Result<(u8, u8), PlatformError> {
    let scheme = active_scheme()?;
    let ac = read_index(true, &scheme, &SUB_PROCESSOR, &PROCTHROTTLEMAX)?;
    let dc = read_index(false, &scheme, &SUB_PROCESSOR, &PROCTHROTTLEMAX)?;
    let parse = |v: u32| {
        u8::try_from(v)
            .ok()
            .filter(|v| *v <= 100)
            .ok_or(PlatformError::Data(
                "maximum processor state out of 0-100 range",
            ))
    };
    Ok((parse(ac)?, parse(dc)?))
}

/// Read the software policy with one active-scheme lookup. Individual
/// settings are optional because Windows can hide/remove processor-class
/// settings on different CPUs or power-policy implementations. The active
/// scheme itself is the only hard requirement for a snapshot.
pub(crate) fn read_windows_ppm_state() -> Result<WindowsPpmState, PlatformError> {
    let scheme = active_scheme()?;
    let read_optional =
        |ac: bool, setting: &GUID| read_index(ac, &scheme, &SUB_PROCESSOR, setting).ok();
    let parse_percent = |v: Option<u32>| v.and_then(|v| u8::try_from(v).ok()).filter(|v| *v <= 100);
    let parse_boost = |v: Option<u32>| {
        v.and_then(|v| u8::try_from(v).ok())
            .and_then(|v| BoostPolicy::try_from(v).ok())
    };
    let values = |ac: bool| WindowsPpmValues {
        epp: parse_percent(read_optional(ac, &PERFEPP)),
        epp1: parse_percent(read_optional(ac, &PERFEPP1)),
        boost_policy: parse_boost(read_optional(ac, &PERFBOOSTMODE)),
        max_freq_mhz: read_optional(ac, &PROCFREQMAX),
        min_performance: parse_percent(read_optional(ac, &PROCTHROTTLEMIN)),
        max_performance: parse_percent(read_optional(ac, &PROCTHROTTLEMAX)),
    };
    Ok(WindowsPpmState {
        active_scheme_guid: guid_string(&scheme),
        active_scheme_name: known_scheme_name(&scheme).into(),
        configured_ac_mode: read_configured_mode(true).ok(),
        configured_dc_mode: read_configured_mode(false).ok(),
        effective_mode: effective_mode(),
        ac: values(true),
        dc: values(false),
    })
}

#[cfg(feature = "control")]
#[allow(dead_code)] // wired in W11 (ControlCoordinator's PpmBackend)
fn write_index(
    ac: bool,
    scheme: &GUID,
    subgroup: &GUID,
    setting: &GUID,
    value: u32,
) -> Result<(), PlatformError> {
    unsafe {
        // windows-0.62 signature lottery (verified against generated
        // bindings): scheme = raw *const GUID; subgroup/setting =
        // Option<*const GUID>; AC → WIN32_ERROR, DC → u32.
        let rc = if ac {
            PowerWriteACValueIndex(
                None,
                scheme as *const GUID,
                Some(subgroup as *const GUID),
                Some(setting as *const GUID),
                value,
            )
            .0
        } else {
            PowerWriteDCValueIndex(
                None,
                scheme as *const GUID,
                Some(subgroup as *const GUID),
                Some(setting as *const GUID),
                value,
            )
        };
        if rc != 0 {
            return Err(PlatformError::Os(format!(
                "PowerWrite{}ValueIndex failed (win32 {})",
                if ac { "AC" } else { "DC" },
                rc
            )));
        }
        Ok(())
    }
}

/// Re-apply the scheme whose value index was written so the change takes
/// effect (the powercfg /S pattern: PowerWrite*ValueIndex only touches the
/// store). Reusing the same GUID avoids committing a different scheme if
/// Windows changes the active scheme between the write and the commit.
#[cfg(feature = "control")]
#[allow(dead_code)] // wired in W11 (ControlCoordinator's PpmBackend)
fn commit_active_scheme(scheme: &GUID) -> Result<(), PlatformError> {
    unsafe {
        let rc = PowerSetActiveScheme(None, Some(scheme));
        if rc.0 != 0 {
            return Err(PlatformError::Os(format!(
                "PowerSetActiveScheme failed (win32 {})",
                rc.0
            )));
        }
        Ok(())
    }
}

/// PowrProf implementation of the domain `CpuPolicyBackend` port (M2 write
/// path). Stateless — every call re-resolves the ACTIVE scheme (the user
/// may switch schemes between commands; we always act on what is active).
#[cfg(feature = "control")]
#[allow(dead_code)] // constructed by the ControlCoordinator (W11)
pub(crate) struct PpmBackend;

#[cfg(feature = "control")]
impl phelper_domain::ports::CpuPolicyBackend for PpmBackend {
    fn read_epp(&self) -> Result<(u8, u8), PlatformError> {
        let r = read_epp()?;
        Ok((r.ac, r.dc))
    }

    fn read_epp1(&self) -> Result<(u8, u8), PlatformError> {
        let r = read_epp1()?;
        Ok((r.ac, r.dc))
    }

    fn read_max_freq_mhz(&self) -> Result<(u32, u32), PlatformError> {
        read_max_freq_mhz_acdc()
    }

    fn read_boost_policy(&self) -> Result<(BoostPolicy, BoostPolicy), PlatformError> {
        read_boost_policy()
    }

    fn read_min_performance(&self) -> Result<(u8, u8), PlatformError> {
        read_min_performance()
    }

    fn read_max_performance(&self) -> Result<(u8, u8), PlatformError> {
        read_max_performance()
    }

    fn write_epp(&self, ac: Option<u8>, dc: Option<u8>) -> Result<(), PlatformError> {
        let scheme = active_scheme()?;
        if let Some(v) = ac {
            write_index(true, &scheme, &SUB_PROCESSOR, &PERFEPP, v as u32)?;
        }
        if let Some(v) = dc {
            write_index(false, &scheme, &SUB_PROCESSOR, &PERFEPP, v as u32)?;
        }
        if ac.is_some() || dc.is_some() {
            commit_active_scheme(&scheme)?;
        }
        Ok(())
    }

    fn write_epp1(&self, ac: Option<u8>, dc: Option<u8>) -> Result<(), PlatformError> {
        let scheme = active_scheme()?;
        if let Some(v) = ac {
            write_index(true, &scheme, &SUB_PROCESSOR, &PERFEPP1, v as u32)?;
        }
        if let Some(v) = dc {
            write_index(false, &scheme, &SUB_PROCESSOR, &PERFEPP1, v as u32)?;
        }
        if ac.is_some() || dc.is_some() {
            commit_active_scheme(&scheme)?;
        }
        Ok(())
    }

    fn write_max_freq_mhz(&self, ac: Option<u32>, dc: Option<u32>) -> Result<(), PlatformError> {
        let scheme = active_scheme()?;
        if let Some(v) = ac {
            write_index(true, &scheme, &SUB_PROCESSOR, &PROCFREQMAX, v)?;
        }
        if let Some(v) = dc {
            write_index(false, &scheme, &SUB_PROCESSOR, &PROCFREQMAX, v)?;
        }
        if ac.is_some() || dc.is_some() {
            commit_active_scheme(&scheme)?;
        }
        Ok(())
    }

    fn write_boost_policy(
        &self,
        ac: Option<BoostPolicy>,
        dc: Option<BoostPolicy>,
    ) -> Result<(), PlatformError> {
        let scheme = active_scheme()?;
        if let Some(mode) = ac {
            write_index(
                true,
                &scheme,
                &SUB_PROCESSOR,
                &PERFBOOSTMODE,
                u8::from(mode) as u32,
            )?;
        }
        if let Some(mode) = dc {
            write_index(
                false,
                &scheme,
                &SUB_PROCESSOR,
                &PERFBOOSTMODE,
                u8::from(mode) as u32,
            )?;
        }
        if ac.is_some() || dc.is_some() {
            commit_active_scheme(&scheme)?;
        }
        Ok(())
    }

    fn write_min_performance(&self, ac: Option<u8>, dc: Option<u8>) -> Result<(), PlatformError> {
        let scheme = active_scheme()?;
        if let Some(v) = ac {
            write_index(true, &scheme, &SUB_PROCESSOR, &PROCTHROTTLEMIN, v as u32)?;
        }
        if let Some(v) = dc {
            write_index(false, &scheme, &SUB_PROCESSOR, &PROCTHROTTLEMIN, v as u32)?;
        }
        if ac.is_some() || dc.is_some() {
            commit_active_scheme(&scheme)?;
        }
        Ok(())
    }

    fn write_max_performance(&self, ac: Option<u8>, dc: Option<u8>) -> Result<(), PlatformError> {
        let scheme = active_scheme()?;
        if let Some(v) = ac {
            write_index(true, &scheme, &SUB_PROCESSOR, &PROCTHROTTLEMAX, v as u32)?;
        }
        if let Some(v) = dc {
            write_index(false, &scheme, &SUB_PROCESSOR, &PROCTHROTTLEMAX, v as u32)?;
        }
        if ac.is_some() || dc.is_some() {
            commit_active_scheme(&scheme)?;
        }
        Ok(())
    }

    fn read_windows_ppm_state(&self) -> Result<Option<WindowsPpmState>, PlatformError> {
        read_windows_ppm_state().map(Some)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Change-detector: GUIDs must stay byte-identical to winnt.h.
    #[test]
    fn guids_match_winnt() {
        fn t(g: &GUID) -> (u32, u16, u16, [u8; 8]) {
            (g.data1, g.data2, g.data3, g.data4)
        }
        assert_eq!(
            t(&SUB_PROCESSOR),
            (
                0x54533251,
                0x82be,
                0x4824,
                [0x96, 0xc1, 0x47, 0xb6, 0x0b, 0x74, 0x0d, 0x00]
            )
        );
        assert_eq!(
            t(&PERFEPP),
            (
                0x36687f9e,
                0xe3a5,
                0x4dbf,
                [0xb1, 0xdc, 0x15, 0xeb, 0x38, 0x1c, 0x68, 0x63]
            )
        );
        assert_eq!(
            t(&PERFEPP1),
            (
                0x36687f9e,
                0xe3a5,
                0x4dbf,
                [0xb1, 0xdc, 0x15, 0xeb, 0x38, 0x1c, 0x68, 0x64]
            )
        );
        assert_eq!(
            t(&PROCFREQMAX),
            (
                0x75b0ae3f,
                0xbce0,
                0x45a7,
                [0x8c, 0x89, 0xc9, 0x61, 0x1c, 0x25, 0xe1, 0x00]
            )
        );
        assert_eq!(
            t(&PERFBOOSTMODE),
            (
                0xbe337238,
                0x0d82,
                0x4146,
                [0xa9, 0x60, 0x4f, 0x37, 0x49, 0xd4, 0x70, 0xc7]
            )
        );
        assert_eq!(
            t(&PROCTHROTTLEMIN),
            (
                0x893dee8e,
                0x2bef,
                0x41e0,
                [0x89, 0xc6, 0xb5, 0x5d, 0x09, 0x29, 0x96, 0x4c]
            )
        );
        assert_eq!(
            t(&PROCTHROTTLEMAX),
            (
                0xbc5038f7,
                0x23e0,
                0x4960,
                [0x96, 0xda, 0x33, 0xab, 0xaf, 0x59, 0x35, 0xec]
            )
        );
    }

    #[test]
    fn windows_mode_guid_mapping_is_explicit() {
        assert_eq!(
            configured_mode_from_guid(USER_MODE_BEST_EFFICIENCY),
            Some(WindowsConfiguredPowerMode::BestEfficiency)
        );
        assert_eq!(
            configured_mode_from_guid(USER_MODE_BALANCED),
            Some(WindowsConfiguredPowerMode::Balanced)
        );
        assert_eq!(
            configured_mode_from_guid(USER_MODE_BEST_PERFORMANCE),
            Some(WindowsConfiguredPowerMode::BestPerformance)
        );
        assert_eq!(configured_mode_from_guid(SUB_PROCESSOR), None);
    }

    #[test]
    fn effective_mode_mapping_is_fail_closed() {
        assert_eq!(
            effective_mode_from_raw(0),
            Some(WindowsEffectivePowerMode::BatterySaver)
        );
        assert_eq!(
            effective_mode_from_raw(6),
            Some(WindowsEffectivePowerMode::MixedReality)
        );
        assert_eq!(effective_mode_from_raw(7), None);
    }

    #[test]
    fn boost_policy_wire_roundtrip() {
        for v in 0u8..=6 {
            let p = BoostPolicy::try_from(v).unwrap();
            assert_eq!(u8::from(p), v);
        }
        assert!(BoostPolicy::try_from(7u8).is_err());
    }
}
